### PR TITLE
Escape.cs Improvements 

### LINKED ISSUE #103: HL7 TX type, obx.5 leading space being trimmed PipeParser
2.4 standard states:
"2.9.48	TX - text data  
String data meant for user display (on a terminal or printer).  Such data would not necessarily be left jus-tified since leading spaces may contribute greatly to the clarity of the presentation to the user.  "

Unless I've missed a config option or rule, escape() function in Escape.cs always trims leading and trailing spaces for type TX i.e.  return result.ToString().Trim();

Perhaps it should be changed to only  TrimEnd?

Example OBX...

Before...
`OBX|23|TX|^Report Line 23||     Sample stored as serological investigations on samples taken within||||||C|||201607270920`

After...
`OBX|23|TX|^Report Line 23||Sample stored as serological investigations on samples taken within||||||C|||201607270920`

The XMLParser works fine as it has KeepAsOriginalNodes property which the PipeParser does not have

### PR DESCRIPTION
**Pull request by milkshakeuk**
### What's in this pull request

1. Removed the use of `Trim()` from `Escape.cs` fixes #103.
2. Changed behaviour of Escape to (mostly) match [hapi implementation](https://github.com/hapifhir/hapi-hl7v2/blob/master/hapi-base/src/main/java/ca/uhn/hl7v2/parser/DefaultEscaping.java).
3. Adds unit tests (as there were none before) to ensure Escape behaves correctly ([some borrowed from hapi](https://github.com/hapifhir/hapi-hl7v2/blob/master/hapi-test/src/test/java/ca/uhn/hl7v2/parser/EscapeTest.java)) others not.
4. Change the default hexadecimal escape sequences for carriage return `\r` to `\X0D\` from `\X000d\`.
5. Make line feed / carriage return hexadecimal escape sequences configurable so as to allow people to go back to the previous escape sequences which was `\X000d\` for carriage returns.
6. Add `.gitattributes` file to prevent the line endings of text files being changed on checkout (as this was breaking some tests when running on linux).

Could potentially be a breaking change for those relying on existing behaviour but this implementation should be more "correct" in line with the hl7 standards, plus the next release is a Major one anyway so breaking changes are expected.

### Hexadecimal line feed and carriage return escape sequence configuration
The escape sequence for line feed `\n` and carriage return `\r` are now configurable to 1 of 3 values each respectively.

example `App.config` configuration:
```
<configSections>
  <section name="EscapingConfiguration" type="NHapi.Base.Model.Configuration.EscapingConfigurationSection, NHapi.Base"/>
</configSections>
...
<EscapingConfiguration>
  <HexadecimalEscaping lineFeedHexadecimal="X0A" carriageReturnHexadecimal="X0D"/>
</EscapingConfiguration>
```

Possible values for `lineFeedHexadecimal` are `X0A`, `X00A` and `X000a` (they map to an enum)
Possible values for `carriageReturnHexadecimalare` are `X0D`, `X00D` and `X000d` (they map to an enum)

If the configuration isn't specified in the `App.config` the default values are `X0A` for line feed and `X0D` for carriage return.

### CODE REVIEW

**Comment by milkshakeuk** [comment]
Will look into the failing tests tomorrow.

**Comment by milkshakeuk** [comment]
Ok one of the tests that is failing is failing because I changed `Escape.cs`.
```
X TestValidHl7Data [1s 6ms]
Error Message:
   Expected string length 39 but was 31. Strings differ at index 8.
Expected: "Th\\T\\is\\E\\.br\\E\\is\\E\\.br\\E\\A T\\F\\est\\E\\"
But was:  "Th\\T\\is\\.br\\is\\.br\\A T\\F\\est\\E\\"
----------------------^

Stack Trace:
   at NHapi.NUnit.ParserTest.TestValidHl7Data() in D:\a\nHapi\nHapi\tests\NHapi.NUnit\ParserTest.cs:line 147
```

Hwever, I beleive the actual result i.e. `Th\\T\\is\\.br\\is\\.br\\A T\\F\\est\\E\\` is correct since the starting value `Th&is\.br\is\.br\A T|est\` and contains formatted text which should which should not be re-escaped i.e. `\.br\` should be left intact  as it is indecating a carrage return, the escape character `\` either side in this instance should not be escaped to `\E\`.

So ill update the test and push those changes along with the stylecop warning fixes.

The second failing test...
```
X UnEscapesData [5ms]
Error Message:
   Expected string length 122 but was 128. Strings differ at index 32.
Expected: "...39;Thirty days have September,\rApril\nJune,\nand November.\nW..."
But was:  "...39;Thirty days have September,\\X000d\\April\nJune,\nand Novem..."
---------------------------------------------^

Stack Trace:
   at NHapi.NUnit.ParserTest.UnEscapesData() in D:\a\nHapi\nHapi\tests\NHapi.NUnit\ParserTest.cs:line 174
```
This one requires a discussion since its failing because of a Unicode hexadecimal representation of a carriage return i.e. `\X000d\` this is one of the escape sequences that is applied when someone adds a `\r` (carriage return) to their text value since this has a special meaning in hl7 indicating the end of a segment.

This is what the hl7 v24 standard says at section 2.10.5

> 2.10.5 Hexadecimal
When the hexadecimal escape sequence (\Xdddd...\) is used the X should be followed by 1 or more pairs of
hexadecimal digits (0, 1, . . . , 9, A, . . . , F). Consecutive pairs of the hexadecimal digits represent 8-bit
binary values. The interpretation of the data is entirely left to an agreement between the sending and receiving applications that is beyond the scope of this Standard.

Both Hapi and nHapi currently use the Unicode hexadecimal representation of the carriage return i.e. `\X000d\` rather than the utf-8 hexadecimal representation i.e. `\X0D\`.

This Pull Request changes what nHapi uses from `\X000d\` to `\X0D\` hense the failing test here.

Other hl7 libraries such as [HL7-dotnetcore](https://github.com/Efferent-Health/HL7-dotnetcore/blob/9ca6f4b907960e062f35163283708ff2b6ceb1a7/src/Encoding.cs#L94) which is based from the java library [hl7inspector](https://github.com/elomagic/hl7inspector/blob/7a95275db6809af1eb914f98c1830730794680c1/src/main/java/de/elomagic/hl7inspector/hl7/Hl7Encoder.java#L61) use the latter.

Also, Intersystems who are the company behind the integration engine software ensemble also suggest to [use the latter](https://docs.intersystems.com/latest/csp/docbook/Doc.View.cls?KEY=EHL72_escape_sequences). 

I would like to use `\X0D\` also but that would mean a breaking change, this should be fine since this will be in a new major version of nHapi.

@duaneedwards @ryankelley  @AMCN41R what are your oppinions on this one?

**Comment by duaneedwards** [comment]
Was a bit concerned about the first change but if I understand this right, you are basically looking to undo the changes made in this commit?

https://github.com/nHapiNET/nHapi/commit/521934dab56d75a86c83fefcfcdaa5bf108df6fd#diff-16e92736eac2a191a20e92f6a74ee9ac812c2c31ba196ec1427d69ca4dda37e7

It looks like this was previously set to expect the value you are proposing to change it to now?

Otherwise the changes look fine, do agree with the idea of putting these behind a major release as it's highly likely someone might run into issues due to some particular system encoding / decoding things some particular way.

**Comment by milkshakeuk** [comment]
> Was a bit concerned about the first change but if I understand this right, you are basically looking to undo the changes made in this commit?
> 
> [521934d#diff-16e92736eac2a191a20e92f6a74ee9ac812c2c31ba196ec1427d69ca4dda37e7](https://github.com/nHapiNET/nHapi/commit/521934dab56d75a86c83fefcfcdaa5bf108df6fd#diff-16e92736eac2a191a20e92f6a74ee9ac812c2c31ba196ec1427d69ca4dda37e7)
Yes however [that](https://github.com/nHapiNET/nHapi/commit/521934dab56d75a86c83fefcfcdaa5bf108df6fd#diff-16e92736eac2a191a20e92f6a74ee9ac812c2c31ba196ec1427d69ca4dda37e7R150) change was only made to make the tests pass, since I assumed it should have just passed (that was done a long time ago 😁)
>
> It looks like this was previously set to expect the value you are proposing to change it to now?

Yes since this is the correct behaviour (from what I have come to understand anyway, plus it is in line with hapi)

> Otherwise the changes look fine, do agree with the idea of putting these behind a major release as it's highly likely someone might run into issues due to some particular system encoding / decoding things some particular way.

I'm still looking into the second one, just in case, as I don't want to introduce anything which isn't correct as far as the standards are concerned.

**Comment by milkshakeuk** [comment]
@duaneedwards @AMCN41R having looked further into [HL7-dotnetcore](https://github.com/Efferent-Health/HL7-dotnetcore/blob/9ca6f4b907960e062f35163283708ff2b6ceb1a7/src/Encoding.cs#L94) and [hl7inspector](https://github.com/elomagic/hl7inspector/blob/7a95275db6809af1eb914f98c1830730794680c1/src/main/java/de/elomagic/hl7inspector/hl7/Hl7Encoder.java#L61) they actually uses `\X00D\` for `\r` (carriage return) and `\X00A\` for `\n` (line feeds) which is different to hapi which uses `\X000d\` and Intersystems which says `\XOD\` and `\X0A\` respectively so... the question is which one should nHapi use?

**Comment by milkshakeuk** [comment]
@duaneedwards @AMCN41R I asked the question in the hl7.org zulip chat and here are the responses:
image
It looks like it's mostly up to us but sounds like `\X0D\` and `\X0A\` might be the way to go.

In the future we can make it configurable instead.

**Comment by duaneedwards** [comment]
Interesting, would it be much work to make it configurable?

I'm thinking that ideally if it were going to be changed from ```\X000d\``` to ```\X0D\``` then perhaps providing the escape hatch back to the previous behaviour at the same time would also be worth the effort if it's within reason.

**Comment by milkshakeuk** [comment]
@duaneedwards 
> Interesting, would it be much work to make it configurable?
> 
> I'm thinking that ideally if it were going to be changed from `\X000d\` to `\X0D\` then perhaps providing the escape hatch back to the previous behaviour at the same time would also be worth the effort if it's within reason.

I'm not sure how difficult it would be to make it configurable but I'll look into it, there was one final reply on the hl7 zulip chat:

image

**Comment by milkshakeuk** [comment]
@duaneedwards ok the escape sequence for line feed `\n` and carriage return `\r` are now configurable to 1 of 3 values each respectively.

```
<configSections>
  <section name="EscapingConfiguration" type="NHapi.Base.Model.Configuration.EscapingConfigurationSection, NHapi.Base"/>
</configSections>
...
<EscapingConfiguration>
  <HexadecimalEscaping lineFeedHexadecimal="X0A" carriageReturnHexadecimal="X0D"/>
</EscapingConfiguration>
```

Possible values for `lineFeedHexadecimal` are `X0A`, `X00A` and `X000a` (they map to an enum)
Possible values for `carriageReturnHexadecimalare` are `X0D`, `X00D` and `X000d` (they map to an enum)

If the configuration isn't specified in the `App.config` the default values are `X0A` for line feed and `X0D` for carriage return.

**Review by AMCN41R — APPROVED** [review]

**Pull request merged**
