### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Usualdosage**
According to the file headers, this was originally licensed under the MPL 1.1. Would like to use the MPL 2.0 template as our primary license.

/* <summary>The contents of this file are subject to the Mozilla Public License Version 1.1 
/// (the "License"); you may not use this file except in compliance with the License. 
/// You may obtain a copy of the License at http://www.mozilla.org/MPL/ 
/// Software distributed under the License is distributed on an "AS IS" basis, 
/// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the 
/// specific language governing rights and limitations under the License. 
/// The Original Code is "AbstractMessage.java".  Description: 
/// "A default implementation of Message" 
/// The Initial Developer of the Original Code is University Health Network. Copyright (C) 
/// 2001.  All Rights Reserved. 
/// Contributor(s): ______________________________________. 
/// Alternatively, the contents of this file may be used under the terms of the 
/// GNU General Public License (the  “GPL”), in which case the provisions of the GPL are 
/// applicable instead of those above.  If you wish to allow use of your version of this 
/// file only under the terms of the GPL and not to allow others to use your version 
/// of this file under the MPL, indicate your decision by deleting  the provisions above 
/// and replace  them with the notice and other provisions required by the GPL License.  
/// If you do not delete the provisions above, a recipient may use your version of 
/// this file under either the MPL or the GPL. 
*/

### CODE REVIEW

**Comment by Usualdosage** [comment]
@milkshakeuk Are you ok with this license? Wanted to confirm with you.

**Comment by milkshakeuk** [comment]
@Usualdosage, @duaneedwards I am not sure what the legal ramifications of changing the license is.

Do we want to change it? if so are we sure we want MPL2.0 or would we want LGPL2.1 or some other preferred license.

**Comment by duaneedwards** [comment]
IANAL but according to the following: https://www.mozilla.org/en-US/MPL/2.0/Revision-FAQ/#:~:text=Yes%2C%20you%20can%2C%20because%20MPL,from%20MPL%202.0%20Exhibit%20A.

You should be able to change the license to MPL 2.0 from MPL 1.1.

Some further info on the differences between versions:

https://tldrlegal.com/license/mozilla-public-license-1.1-(mpl-1.1)

vs 

https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

**Comment by milkshakeuk** [comment]
@Usualdosage your branch needs rebasing from master so that only the one commit pertaining to th license change is included. 

Also I think of we are including the new license file inside the repo it can removed from the header of the c# files.

**Comment by milkshakeuk** [comment]
@Usualdosage I have rebased the branch for you if you need to sync locally you can either delete your local branch and check it out again or run the following command line steps.


`git checkout add-license-1` if you don't already have the branch checked out
`git fetch` to ensure your remote tracking branches are up to date.
`git reset --hard origin/add-license-1` to ensure your local branch is exactly in line with the remote branch.

all that needs to happen now is either remove the license headers from the C# files or update the license headers to reference MPL2.0 instead.

**Comment by Usualdosage** [comment]
> @Usualdosage your branch needs rebasing from master so that only the one commit pertaining to th license change is included.
> 
> Also I think of we are including the new license file inside the repo it can removed from the header of the c# files.

Rebased. I'll update the license and remove the headers in the next commit.

**Comment by milkshakeuk** [comment]
@Usualdosage are you still working on this?

**Comment by Usualdosage** [comment]
Yeah sorry, had to take a brief hiatus, but I’m back now.

**Comment by milkshakeuk** [comment]
@Usualdosage how come this was closed?

**Comment by Usualdosage** [comment]
New PC, had to regen a GitHub key. Will open a new PR shortly.

**Comment by milkshakeuk** [comment]
@Usualdosage you know the branch still exists right? you could just check it back out again, shall I re-open this PR?

**Pull request closed without merging**
