### PR TITLE
Fix some static analysis issues

### PR DESCRIPTION
**Pull request by PhantomGrazzler**
* [Made parameter names match base class declarations.](https://github.com/nHapiNET/nHapi/commit/b3f691a8e56679a008a442c2be03bca16df64366)
* [Simplified some checks for "not equal".](https://github.com/nHapiNET/nHapi/commit/6951632ceb1920ccdc36a40f76fc1d7872cf6c0d)
* [Made fields that are only assigned in the constructor "readonly".](https://github.com/nHapiNET/nHapi/commit/39569024f623a032b9107ac85ad8577108911a73)

### CODE REVIEW

**Review by milkshakeuk — COMMENTED** [review]
@PhantomGrazzler are these all static code analysis changes? Are we sure these fields only get set at construction time?

**Comment by PhantomGrazzler** [comment]
> @PhantomGrazzler are these all static code analysis changes? Are we sure these fields only get set at construction time?

Yes, these are all static analysis changes that I saw on Codacy (https://app.codacy.com/gh/nHapiNET/nHapi/pullRequest?prid=9304251).

My understanding of the `readonly` keyword (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly) is that the code would fail to compile if there is an attempt to assign to these fields outside of constructor or field declaration. It is entirely possible that my understanding is flawed though :)

**Comment by milkshakeuk** [comment]
@PhantomGrazzler okay cool, makes sense.

**Comment by milkshakeuk** [comment]
@PhantomGrazzler thanks for the PR.

**Pull request merged**
