### PR TITLE
Fixed Event Mappings for Model.V23

### PR DESCRIPTION
**Pull request by ddebrecenijr**

### CODE REVIEW

**Comment by ddebrecenijr** [comment]
Fixed Issues related to #79 and #67, PR #68 is incomplete.

**Comment by milkshakeuk** [comment]
@Usualdosage you do realise these event map files are generated so the next time we run the genrator (after we obtain the database) is going to overewrite these changes, I belive one of the other pull requests made changes #68

**Comment by Usualdosage** [comment]
@milkshakeuk I didn't realize they were auto generated. My mistake. Reverting.

**Comment by ddebrecenijr** [comment]
Referencing #121 for context

@milkshakeuk @Usualdosage I worked on this some time ago and haven't really touched the nHapi stuff since. And just to have a complete context, so you are saying that there exists some database you grab these mappings from and that they are wrong as defined in `NHapi20/NHapi.Base/SourceGeneration/EventMappingGenerator.cs`
And that these changes will be overwritten at what point? You manually running the Model Generator? It looks like there is a build task `NHapi20/default.ps1` that does
```
Task BuildModels {
#    Exec { msbuild "Hl7Models.sln" /t:Build /p:Configuration=Debug /v:quiet}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.1 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.2 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.3 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.3.1 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.4 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.5 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
#    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.5.1 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.6 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.7 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.7.1 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.8 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
    Exec { ModelGenerator\Bin\Debug\ModelGenerator.exe /BasePath . /Version 2.8.1 /ConnectionString "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\hl7_72_HQ.mdb;"}
}
```

So it doesn't appear that these things are being regenerated to me nor is it part of the default build. I may be wrong I did not look very deeply into it. 

But a question probably worth asking might be, why would you want to regenerate these often or even all the time, which it sounds like that's a thing? Does the database change often for these versions? I wouldn't think to expect this behavior out of a build.

**Comment by milkshakeuk** [comment]
@ddebrecenijr the Hl7 normative database something that is maintained and updated by a member of Hl7.org called Frank Oemig.

All the information about the structure of each message type of each version of the Hl7 standard is in this database.

This project uses this database to generate the versioned NHapi classes and event mappings in the repository.

What should happen is that every time we we make changes we should regenerate the source code. We plan of having a CI/CD pipeline to automate this process.

If we want to support newer versions of Hl7 its key to have an up to date version of the normative database.

Chances are the changes to the eventmap you did in the PR would also be fixed by using a newer version of the normative database, if not we should feed back to Hl7 org or look at how we are reading the information from the database and fix that's assuming there is a mistake in the source generator.

**Comment by ddebrecenijr** [comment]
@milkshakeuk Thanks for the info, was not aware of that and makes sense. I'm not concerned about whether or not what I did fixed it or not, it sounds like if anything its more of a bandage for the root.  
Something that might be a "nice to have" is a way of knowing whether or not the mdb that were used are now obsolete. Maybe can be solved by your proposed CI/CD pipeline, but potentially to also kick this off on some modification to the database (if possible).

Glad to see this is going back into active dev, good luck with it!

**Comment by milkshakeuk** [comment]
@ddebrecenijr I checked the hapi event maps and they have the same as what's in your fix, for now I'm going to merge it back into master, since it will be a while yet before we generate new models and event maps etc from the database.

**Comment by milkshakeuk** [comment]
Actually looks like it's [already in](https://github.com/nHapiNET/nHapi/commit/289bc505849ceb119540ec4cd7e58f0ff4c6904c).

**Pull request merged**
